/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class imu_lcmt implements lcm.lcm.LCMEncodable
{
    /**
     * LCM Type: float[4]
     */
    public float q[];

    /**
     * LCM Type: float[3]
     */
    public float gyro[];

    /**
     * LCM Type: float[3]
     */
    public float accel[];

    public long timestamp;

 
    public imu_lcmt()
    {
        q = new float[4];
        gyro = new float[3];
        accel = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x39b734434bcce8e2L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.imu_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.imu_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.q[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.gyro[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.accel[a]); 
        }
 
        outs.writeLong(this.timestamp); 
 
    }
 
    public imu_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public imu_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.imu_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.imu_lcmt o = new lcmtypes.imu_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.q = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.q[a] = ins.readFloat();
        }
 
        this.gyro = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.gyro[a] = ins.readFloat();
        }
 
        this.accel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.accel[a] = ins.readFloat();
        }
 
        this.timestamp = ins.readLong();
 
    }
 
    public lcmtypes.imu_lcmt copy()
    {
        lcmtypes.imu_lcmt outobj = new lcmtypes.imu_lcmt();
        outobj.q = new float[(int) 4];
        System.arraycopy(this.q, 0, outobj.q, 0, 4); 
        outobj.gyro = new float[(int) 3];
        System.arraycopy(this.gyro, 0, outobj.gyro, 0, 3); 
        outobj.accel = new float[(int) 3];
        System.arraycopy(this.accel, 0, outobj.accel, 0, 3); 
        outobj.timestamp = this.timestamp;
 
        return outobj;
    }
 
}

