"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class imu_lcmt(object):

    __slots__ = ["q", "gyro", "accel", "timestamp"]

    __typenames__ = ["float", "float", "float", "int64_t"]

    __dimensions__ = [[4], [3], [3], None]

    def __init__(self):
        self.q = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.gyro = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.accel = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.timestamp = 0
        """ LCM Type: int64_t """

    def encode(self):
        buf = BytesIO()
        buf.write(imu_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4f', *self.q[:4]))
        buf.write(struct.pack('>3f', *self.gyro[:3]))
        buf.write(struct.pack('>3f', *self.accel[:3]))
        buf.write(struct.pack(">q", self.timestamp))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != imu_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return imu_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = imu_lcmt()
        self.q = struct.unpack('>4f', buf.read(16))
        self.gyro = struct.unpack('>3f', buf.read(12))
        self.accel = struct.unpack('>3f', buf.read(12))
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if imu_lcmt in parents: return 0
        tmphash = (0x39b734434bcce8e2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if imu_lcmt._packed_fingerprint is None:
            imu_lcmt._packed_fingerprint = struct.pack(">Q", imu_lcmt._get_hash_recursive([]))
        return imu_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", imu_lcmt._get_packed_fingerprint())[0]

