"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class leg_control_command_lcmt(object):
    __slots__ = ["tau_ff", "q_des", "qd_des", "kp_joint", "kd_joint", "tau_des"]

    __typenames__ = ["float", "float", "float", "float", "float", "float"]

    __dimensions__ = [[16], [16], [16], [16], [16], [16]]

    def __init__(self):
        self.tau_ff = [ 0.0 for dim0 in range(16) ]
        self.q_des = [ 0.0 for dim0 in range(16) ]
        self.qd_des = [ 0.0 for dim0 in range(16) ]
        self.kp_joint = [ 0.0 for dim0 in range(16) ]
        self.kd_joint = [ 0.0 for dim0 in range(16) ]
        self.tau_des = [ 0.0 for dim0 in range(16) ]

    def encode(self):
        buf = BytesIO()
        buf.write(leg_control_command_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>16f', *self.tau_ff[:16]))
        buf.write(struct.pack('>16f', *self.q_des[:16]))
        buf.write(struct.pack('>16f', *self.qd_des[:16]))
        buf.write(struct.pack('>16f', *self.kp_joint[:16]))
        buf.write(struct.pack('>16f', *self.kd_joint[:16]))
        buf.write(struct.pack('>16f', *self.tau_des[:16]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != leg_control_command_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return leg_control_command_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = leg_control_command_lcmt()
        self.tau_ff = struct.unpack('>16f', buf.read(64))
        self.q_des = struct.unpack('>16f', buf.read(64))
        self.qd_des = struct.unpack('>16f', buf.read(64))
        self.kp_joint = struct.unpack('>16f', buf.read(64))
        self.kd_joint = struct.unpack('>16f', buf.read(64))
        self.tau_des = struct.unpack('>16f', buf.read(64))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if leg_control_command_lcmt in parents: return 0
        tmphash = (0x9de2bbd49b05e39) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if leg_control_command_lcmt._packed_fingerprint is None:
            leg_control_command_lcmt._packed_fingerprint = struct.pack(">Q", leg_control_command_lcmt._get_hash_recursive([]))
        return leg_control_command_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

